{
 "title": "PING监控",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Switch",
    "query": {
     "query": "label_values(snmp_uptime,device_name)"
    }
   },
   {
    "name": "Tenant",
    "label": "租户",
    "query": {
     "query": "label_values(snmp_uptime,tenant)"
    }
   },
   {
    "name": "Level",
    "label": "日志等级",
    "query": "critical : 1, error : 2, warning : 3, info : 4, debug : 5, trace : 6"
   },
   {
    "name": "Brief",
    "query": {}
   },
   { "name": "Text", "label": "关键字" }
  ]
 },
 "panels": [
  {
   "title": "通断监测",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ping_result_code", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "广播流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "sum by(band_ip) (rate(snmp_interface_ifInNUcastPkts[1m])) + sum by(band_ip) (rate(snmp_interface_ifOutNUcastPkts[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "时延",
   "type": "bargauge",
   "gridPos": { "h": 24, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_average_response_ms{device_name=~\"$Switch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InOut流量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(band_ip)(rate(snmp_interface_ifInOctets[1m])*8/1024/1024 + rate(snmp_interface_ifOutOctets[1m])*8/1024/1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InOut丢包",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "targets": [
    {
     "expr": "sum by(band_ip)(rate(snmp_interface_ifInDiscards[1m]) + rate(snmp_interface_ifOutDiscards[1m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InOut Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(band_ip) (rate(snmp_interface_ifInErrors[1m]) + rate(snmp_interface_ifOutErrors[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(tenant) (rate(snmp_interface_ifOutErrors{}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "在线接口数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 16 },
   "targets": [
    {
     "expr": "count by(band_ip)(snmp_interface_ifOperStatus{tenant=\"$Tenant\", ifDescr!~\"Vlan.+|InL.+|NU.+|ME.+|Con.+\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}