{
 "title": "交换机详情",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Switch",
    "label": "交换机名称",
    "query": "select dev.name from device dev\ninner join catalog ca on ca.code = dev.catalog_code\nwhere ca.name = 'switch'\norder by dev.name"
   }
  ]
 },
 "panels": [
  {
   "title": "系统启动时间",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_uptime{hostname=\"$Switch\"} / 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5分钟总计流量[out]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(snmp_interface_ifOutOctets{hostname=\"$Switch\"}[1m])*8/1024/1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5分钟最大流量[out]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(snmp_interface_ifOutOctets{hostname=\"$Switch\"}[1m])*8/1024/1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU温度",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_hw_temperature_usage{hostname=\"$Switch\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "内存使用率%",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_hw_mem_usage{hostname=\"$Switch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "时延监测",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "targets": [
    {
     "expr": "ping_average_response_ms{device_name=\"$Switch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU使用率%",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_hw_cpu_usage{hostname=\"$Switch\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5分钟总计流量[in]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(snmp_interface_ifInOctets{hostname=\"$Switch\"}[1m])*8/1024/1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5分钟最大流量[in]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(snmp_interface_ifInOctets{hostname=\"$Switch\"}[5m])*8/1024/1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "当前UP接口",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "snmp_interface_ifOperStatus{hostname=\"$Switch\", ifDescr !~ \"Vlan.*|NU.*|Con.*|ME.*|InL.*\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "在线接口",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "count(snmp_interface_ifOperStatus{device_name=\"$Switch\", ifDescr !~ \"Vlan.*|NU.*|Con.*|ME.*|InL.*\"} == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ping_result_code{device_name=\"$Switch\"} ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}