{
 "title": "交换机日志",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Tenant",
    "label": "学校",
    "query": "select name from tenant where deleted_at is null"
   },
   {
    "name": "Hostname",
    "label": "设备名",
    "query": "select name from device where deleted_at is null"
   },
   {
    "name": "Level",
    "label": "日志等级",
    "query": "critical : 1, error : 2, warning : 3, info : 4, debug : 5, trace : 6"
   },
   { "name": "text", "label": "关键字" },
   {
    "name": "Brief",
    "label": "事件概述",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Level分布",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(level) (count_over_time({__name=\"tail\", brief!=\"NBRCHGTRAP\"} | tenant =~ `$Tenant` | hostname =~ `$Hostname` | brief =~ `${Brief}` | loglevel <= $Level |~ `(?i)$text` [24h]))"
    }
   ]
  },
  {
   "title": "交换机日志分布",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (hostname) (count_over_time({__name=\"tail\", brief!=\"NBRCHGTRAP\"} | tenant =~ `$Tenant` | hostname =~ `$Hostname` | brief =~ `${Brief}` | loglevel <= $Level |~ `(?i)$text` [$__auto]))"
    }
   ]
  },
  {
   "title": "事件分布",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(brief) (count_over_time({__name=\"tail\", brief!=\"NBRCHGTRAP\"} | tenant =~ `$Tenant` | hostname =~ `$Hostname`  | loglevel <= $Level |~ `(?i)$text` [30m]))"
    }
   ]
  },
  {
   "title": "登录失败",
   "type": "stat",
   "gridPos": { "h": 14, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({__name=\"tail\"} |= \"Failed to login\" != \"public key\"[24h]))"
    }
   ]
  },
  {
   "title": "STP事件",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({__name=\"tail\"} |~ \"(?i)stp\"[24h]))"
    }
   ]
  },
  {
   "title": "中断次数",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ping_result_code)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "连通性监控",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "expr": "ping_average_response_ms", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "日志统计",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({__name=\"tail\", brief!=\"NBRCHGTRAP\"} | tenant =~ `$Tenant` | hostname =~ `$Hostname` | brief =~ `${Brief}` | loglevel <= $Level |~ `(?i)$text` [5m]))"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "交换机日志",
   "type": "logs",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{__name=\"tail\", ddModuleName!=\"01SSH\", ddModuleName!=\"01SHELL\", ddModuleName!=\"01DEFD\", brief!=\"NBRCHGTRAP\"} | tenant =~ `$Tenant` | hostname =~ `$Hostname` | brief =~ `${Brief}` | loglevel <= $Level |~ `(?i)$text`"
    },
    {
     "expr": "{ddModuleName=\"01SSH\", brief!=\"NBRCHGTRAP\"} | tenant =~ `$Tenant` | hostname =~ `$Hostname` | brief =~ `${Brief}` | loglevel <= $Level |~ `(?i)$text` | regexp `message=\"(?P<event>.*?)\\. \\(IP=(?P<client_ip>\\S+),.*?UserName=(?P<user>\\S+)[\\)|,]( Times=(?P<retry>\\d+), FailedReason=(?P<reason>.*)\\))?`"
    },
    {
     "expr": "{ddModuleName=\"01SHELL\", brief!=\"NBRCHGTRAP\"} | tenant =~ `$Tenant` | hostname =~ `$Hostname` | brief =~ `${Brief}` | loglevel <= $Level |~ `(?i)$text` | regexp `message=\"(?P<event>.*?)\\. \\(.*?User=(?P<user>\\S+),.*?Command=\"(?P<command>.*?)\"`"
    },
    {
     "expr": "{ddModuleName=\"01DEFD\", brief!=\"NBRCHGTRAP\"} | tenant =~ `$Tenant` | hostname =~ `$Hostname` | brief =~ `${Brief}` | loglevel <= $Level |~ `(?i)$text` | regexp `message=\"(?P<event>.*?)\\. \\(.*?ExceededPacketCount=(?P<exceed_pkt_count>\\d+)\\)\"`"
    }
   ]
  }
 ]
}