{
 "title": "概览",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "组织",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(snmp_uptime) by (tenant))",
     "legendFormat": "学校"
    },
    {
     "expr": "count(count(snmp_uptime) by (device_name))",
     "legendFormat": "交换机"
    }
   ]
  },
  {
   "title": "基础信息",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(snmp_uptime) by (hostname))",
     "legendFormat": "设备"
    },
    {
     "expr": "count(count(snmp_uptime) by (device_model))",
     "legendFormat": "设备类型"
    },
    {
     "expr": "count(count(snmp_uptime) by (rack))",
     "legendFormat": "机柜"
    }
   ]
  },
  {
   "title": "站点容量",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 5, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "select s.name, count(temp.rack_code) 当前机柜数, s.rack_capacity 最大机柜数, sum(temp.rack_used) 已使用机柜容量, sum(temp.rack_height) 机柜总容量, s.server_capacity 服务器总容量\r\nfrom site s\r\nleft join (\r\n  select r.site_code, r.code rack_code, ca.rack_used, r.height rack_height\r\n  from rack r\r\n  left join (\r\n    select rack_code, sum((convert(substring_index(frame, '-', -1), signed) - convert(substring_index(frame, '-', 1), signed) + 1)) rack_used \r\n    from device \r\n    where deleted_at is null \r\n    GROUP BY rack_code\r\n  ) ca on ca.rack_code = r.code\r\n) temp on temp.site_code = s.`code`\r\nGROUP BY temp.site_code\r\norder by s.name desc"
    }
   ]
  },
  {
   "title": "5分钟流量排行榜[in]",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, rate(snmp_interface_ifInOctets[5m])*8/1024/1024)",
     "legendFormat": "{{tenant}} | {{hostname}} | {{ident}} | {{ifDescr}} -> {{peer_device}}"
    }
   ]
  },
  {
   "title": "IP地址",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "select count(code) VRF转发表 from vrf where deleted_At is null"
    },
    {
     "dataset": "mysql",
     "rawSql": "select count(code) 网段 from prefix where deleted_At is null"
    },
    {
     "dataset": "mysql",
     "rawSql": "select count(code) IP地址 from ip_address where deleted_At is null"
    }
   ]
  },
  {
   "title": "机柜使用率",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "select concat(s.name, '(', r.name, ')') name, ca.used, r.height capacity\r\nfrom rack r\r\nleft join site s on r.site_code = s.code\r\nleft join (\r\n  select rack_code, sum((convert(substring_index(frame, '-', -1), signed) - convert(substring_index(frame, '-', 1), signed) + 1)) used \r\n  from device\r\n  where deleted_at is null \r\n  GROUP BY rack_code\r\n) ca on ca.rack_code = r.code\r\nwhere r.deleted_at is null\r\norder by s.name desc, r.name"
    }
   ]
  },
  {
   "title": "交换机互联",
   "type": "table",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(snmp_interface_ifInOctets{peer_device!=\"\"}[24h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5分钟流量排行榜[out]",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, rate(snmp_interface_ifOutOctets[5m])*8/1024/1024)",
     "legendFormat": "{{tenant}} | {{hostname}} | {{ident}} | {{ifDescr}} -> {{peer_device}}"
    }
   ]
  }
 ]
}